export const AddStory = {
  ADD_SPRINT_REQUEST: 'ADD_STORY_ADD_SPRINT_REQUEST',
  ADD_SPRINT_SUCCESS: 'ADD_STORY_ADD_SPRINT_SUCCESS',
  ADD_SPRINT_FAIL: 'ADD_STORY_ADD_SPRINT_FAIL',
};

export const PlanningView = {
  GET_SPRINT_DETAILS_REQUEST: 'PLANNING_VIEW_GET_SPRINT_DETAILS_REQUEST',
  GET_SPRINT_DETAILS_SUCCESS: 'PLANNING_VIEW_GET_SPRINT_DETAILS_SUCCESS',
  GET_SPRINT_DETAILS_FAIL: 'PLANNING_VIEW_GET_SPRINT_DETAILS_FAIL',
  GET_SPRINT_STORIES_REQUEST: 'PLANNING_VIEW_GET_SPRINT_STORIES_REQUEST',
  GET_SPRINT_STORIES_SUCCESS: 'PLANNING_VIEW_GET_SPRINT_STORIES_SUCCESS',
  GET_SPRINT_STORIES_FAIL: 'PLANNING_VIEW_GET_SPRINT_STORIES_FAIL',
};
